# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://hwilu.github.io
date_format: "ordinal"
title: HwiLu's 博客
subtitle: "day day up"
description: "good good study"
keywords: HoweLu, HwiLu
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: HwiLu
organization: 
organization_url: 
github_username: HwiLu
location: Shenzhen, China
email: hw1993.lu@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /archives/
    label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: HwiLu/hwilu.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: HwiLu
    repo: blog-comments
    oauth:
        client_id: bdd8820a7c374fc76360
        client_secret: 108eff61f58ce177f945aba57547ac4ad849f85b
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: HwiLu
    admin: HwiLu
    repo: blog-comments
    clientID: dbdd8820a7c374fc76360
    clientSecret: 108eff61f58ce177f945aba57547ac4ad849f85b
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
